version: '3'

services:
  main-server:
    build: server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./volumes/web-server:/home

  database-server:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./volumes/database-server:/home

  database-search-engine:
    image: 'elasticsearch'
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - ./volumes/database-search-engine:/home